[package]
name = "artem"
version = "0.3.0"
edition = "2021"
description = "An easy program to convert an image to an ascii image"
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/finefindus/artem"
repository = "https://github.com/finefindus/artem"
catogories = ["command-line-utilities"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#build file
build = "build.rs"

[profile.release]
opt-level = 3

#bin definition
[[bin]]
name = "artem"
path = "src/main.rs"


[build-dependencies]
clap = "3.1.0"
clap_complete = "3.1.0"
clap_mangen = "0.1.2"


[dependencies]
image = "0.24.0"
colored = "2"
clap = "3.1.0"
terminal_size = "0.1.17"

[package.metadata.deb]
section = "graphics"
priority = "optional"
copyrigth = "2022, github.com/finefindus"
assets = [
      ["target/release/artem", "usr/bin/", "755"],
      ["deployment/deb/artem.1", "usr/share/man/man1/artem.1", "644"],
      #the completion file and man page is generated and copied by the build script
      ["deployment/deb/artem.bash", "usr/share/bash-completion/completions/artem", "644"],
]
extended-description = """\
artem is a cli project to convert images to ascii art. By default it uses truecolor, if not support it fallsback to ansi colors.
"""