# Reference:
# https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/

name: release
on:
#for debugging purposes
  [push]
  # release:
  #   types: [created]

jobs:

  release_assets:
    name: Release assets
    # needs: create_release # we need to know the upload URL
    runs-on: ${{ matrix.platform }} # we run many different builds
    strategy:
      matrix:
        platform: [ubuntu-latest, 
        #disable macos since it is 10x more expensive and currently not needed 
        #macos-latest, 
        #same with windows
        #windows-latest
        ]
        rust:
          - stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      #use caching for cargo build 
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build artem release
        uses: actions-rs/cargo@v1
        continue-on-error: false 
        #todo use cross to compile for more targets
        with:
          command: build 
          args: --locked --release --verbose

          #from: https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml
      - name: Extract Version Number
        shell: bash
        run: echo "PROJECT_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV

      - name: Compress release files
        shell: bash
        run: tar -czvf artem--v$PROJECT_VERSION-${{ matrix.platform }}.tar.gz target/release/artem

      - name: Upload Release Build
        uses: softprops/action-gh-release@v1
        with:
          files: artem--v${{ PROJECT_VERSION }}-${{ matrix.platform }}.tar.gz
          draft: true
          prerelease: true


  release_deb:
    name: Create Debian
    # needs: create_release # we need to know the upload URL
    runs-on: ${{ matrix.platform }} # we run many different builds
    strategy:
      matrix:
        platform: [ubuntu-latest]
        rust:
          - stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      #use caching for cargo build 
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo deb
        uses: actions-rs/cargo@v1
        continue-on-error: false 
        with:
          command: install
          args: cargo-deb

      - name: Run cargo deb
        uses: actions-rs/cargo@v1
        continue-on-error: false 
        with:
          command: deb

      - name: Upload Debian Package
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/debian/*.deb
          draft: true
          prerelease: true